import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "john",
      email: "admin@admin.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "alex",
      email: "alex@alex.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
    {
      name: "hulk",
      email: "hulk@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  product: [
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: "4.5",
      numReviews: 8,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 50,
      brand: "Adidas",
      rating: "3.5",
      numReviews: 5,
      countInStock: 5,
      description: "A good shirt",
    },
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 45,
      brand: "Gucci",
      rating: "2.7",
      numReviews: 9,
      countInStock: 5,
      description: "A good popular shirt",
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 45,
      brand: "Gucci",
      rating: "2.7",
      numReviews: 9,
      countInStock: 15,
      description: "A good popular pant",
    },
    {
      name: "Fit Pants",
      slug: "fit-pant",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 50,
      brand: "Adidas",
      rating: "3.5",
      numReviews: 5,
      countInStock: 10,
      description: "A good Pant",
    },
    {
      name: "Slim Pant",
      slug: "slim-pant",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 45,
      brand: "Zara",
      rating: "2.7",
      numReviews: 9,
      countInStock: 15,
      description: "A popular shirt",
    },
  ],
};

export default data;
